int enforcou();
void abertura();
void chute();
int jachutou(char letra);
int ganhou();
void desenhaForca();
void escolhePalavra();
int numeroDeErros();
void escolheNivel();
void ranking();
void pontuacao();
void novaPalavra();
void regras();
void verRanking();
int contemPalavra();